# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Correo',
        ),
        migrations.AddField(
            model_name='clientes',
            name='Correo',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
