# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0003_auto_20171012_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('ID_Pedido', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Inicio', models.DateTimeField()),
                ('Fecha_Final', models.DateTimeField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tamales.Clientes')),
            ],
        ),
    ]
