# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0004_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='Cliente',
        ),
    ]
