# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0005_auto_20171012_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='Cliente',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Tamales.Clientes'),
            preserve_default=False,
        ),
    ]
