# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0006_pedidos_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Orden',
            field=models.ManyToManyField(through='Tamales.Productos', to='Tamales.Clientes'),
        ),
        migrations.AddField(
            model_name='productos',
            name='clientes',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Tamales.Clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='inviter',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='productos_clientes', to='Tamales.Clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='pedidos',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Tamales.Pedidos'),
            preserve_default=False,
        ),
    ]
