# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0007_auto_20171012_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Productos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.PositiveSmallIntegerField()),
                ('Total_Pagar', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='Orden',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Usuario',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Tamales.Usuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Precio',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='pedido_productos',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tamales.Clientes'),
        ),
        migrations.AddField(
            model_name='pedido_productos',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tamales.Productos'),
        ),
    ]
