# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0008_auto_20171012_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Cliente',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Tamales.Clientes'),
            preserve_default=False,
        ),
    ]
