# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0009_auto_20171012_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_productos',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='pedido_productos',
            name='Pedido',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Tamales.Pedidos'),
            preserve_default=False,
        ),
    ]
