# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0011_auto_20171018_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default=10, upload_to='albums/images/'),
            preserve_default=False,
        ),
    ]
