# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0012_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='entamalizate/s-storage/img/tamales/'),
        ),
    ]
