# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0014_auto_20171128_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='tamales/'),
        ),
    ]
