# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tamales', '0016_auto_20171206_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_productos',
            name='user',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
