# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamales', '0019_auto_20171206_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='Fecha_Final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Fecha_Inicio',
            field=models.DateField(),
        ),
    ]
